from math import inf

from senseact.math import Interval

l0 = (-inf, None)  # (LOW
l1 = (-inf, None)  # (LOW
l2 = (0, False)  # [0
l3 = (0, True)  # (0
l4 = (-inf, None)  # (LOW
l5 = (1, False)  # [1
l6 = (1, True)  # (1
l7 = (38, True)  # (38
l8 = (40, False)  # [40

r0 = (inf, None)  # HIGH)
r1 = (inf, None)  # HIGH)
r2 = (1, True)  # 1]
r3 = (1, False)  # 1)
r4 = (inf, None)  # HIGH)
r5 = (0, True)  # 0]
r6 = (0, False)  # 0)
r7 = (5, True)  # 5]
r8 = (41, True)  # 41]
r9 = (45, True)  # 45]

i0 = Interval([(l1, r1)])  # (LOW..HIGH)
i1 = Interval([(l1, r2)])  # (LOW..1]
i2 = Interval([(l1, r3)])  # (LOW..1)
i3 = Interval([(l2, r1)])  # [0..HIGH)
i4 = Interval([(l2, r2)])  # [0..1]
i5 = Interval([(l2, r3)])  # [0..1)
i6 = Interval([(l3, r1)])  # (0..HIGH)
i7 = Interval([(l3, r2)])  # (0..1]
i8 = Interval([(l3, r3)])  # (0..1)
i9 = Interval([])  # [1..0] -> ()
i10 = Interval([(l1, r6)])  # (LOW..0)
i11 = Interval([(l6, r1)])  # (1..HIGH)
i12 = Interval([(l2, r7)])  # [0..5]
i13 = Interval([(l7, r8)])  # (38..41]
i14 = Interval([(l8, r9)])  # [40..45]

e0 = Interval([])  # ()
e1 = Interval([((-inf, None),(inf, None))])  # (LOW..HIGH)

print('-----------------------')
print('lower_endpoint:')
print('')
print('id')
print('l0 = ' + str(l0))
print('l1 = ' + str(l1))
print('l2 = ' + str(l2))
print('l3 = ' + str(l3))
print('l4 = ' + str(l4))
print('l5 = ' + str(l5))
print('l6 = ' + str(l6))
print('')
print('less')
print('l0 < l1 = ' + str(l0 < l1))
print('l1 < l2 = ' + str(l1 < l2))
print('l2 < l3 = ' + str(l2 < l3))
print('l3 < l4 = ' + str(l3 < l4))
print('l4 < l5 = ' + str(l4 < l5))
print('l5 < l6 = ' + str(l5 < l6))
print('')
print('less equal')
print('l0 <= l1 = ' + str(l0 <= l1))
print('l1 <= l2 = ' + str(l1 <= l2))
print('l2 <= l3 = ' + str(l2 <= l3))
print('l3 <= l4 = ' + str(l3 <= l4))
print('l4 <= l5 = ' + str(l4 <= l5))
print('l5 <= l6 = ' + str(l5 <= l6))
print('')
print('equal')
print('l0 == l1 = ' + str(l0 == l1))
print('l1 == l2 = ' + str(l1 == l2))
print('l2 == l3 = ' + str(l2 == l3))
print('l3 == l4 = ' + str(l3 == l4))
print('l4 == l5 = ' + str(l4 == l5))
print('l5 == l6 = ' + str(l5 == l6))
print('')
print('greater equal')
print('l0 >= l1 = ' + str(l0 >= l1))
print('l1 >= l2 = ' + str(l1 >= l2))
print('l2 >= l3 = ' + str(l2 >= l3))
print('l3 >= l4 = ' + str(l3 >= l4))
print('l4 >= l5 = ' + str(l4 >= l5))
print('l5 >= l6 = ' + str(l5 >= l6))
print('')
print('greater')
print('l0 > l1 = ' + str(l0 > l1))
print('l1 > l2 = ' + str(l1 > l2))
print('l2 > l3 = ' + str(l2 > l3))
print('l3 > l4 = ' + str(l3 > l4))
print('l4 > l5 = ' + str(l4 > l5))
print('l5 > l6 = ' + str(l5 > l6))
print('')
print('-----------------------')
print('upper_endpoint:')
print('')
print('id')
print('r0 = ' + str(r0))
print('r1 = ' + str(r1))
print('r2 = ' + str(r2))
print('r3 = ' + str(r3))
print('r4 = ' + str(r4))
print('r5 = ' + str(r5))
print('r6 = ' + str(r6))
print('')
print('less')
print('r0 < r1 = ' + str(r0 < r1))
print('r1 < r2 = ' + str(r1 < r2))
print('r2 < r3 = ' + str(r2 < r3))
print('r3 < r4 = ' + str(r3 < r4))
print('r4 < r5 = ' + str(r4 < r5))
print('r5 < r6 = ' + str(r5 < r6))
print('')
print('less equal')
print('r0 <= r1 = ' + str(r0 <= r1))
print('r1 <= r2 = ' + str(r1 <= r2))
print('r2 <= r3 = ' + str(r2 <= r3))
print('r3 <= r4 = ' + str(r3 <= r4))
print('r4 <= r5 = ' + str(r4 <= r5))
print('r5 <= r6 = ' + str(r5 <= r6))
print('')
print('equal')
print('r0 == r1 = ' + str(r0 == r1))
print('r1 == r2 = ' + str(r1 == r2))
print('r2 == r3 = ' + str(r2 == r3))
print('r3 == r4 = ' + str(r3 == r4))
print('r4 == r5 = ' + str(r4 == r5))
print('r5 == r6 = ' + str(r5 == r6))
print('')
print('greater equal')
print('r0 >= r1 = ' + str(r0 >= r1))
print('r1 >= r2 = ' + str(r1 >= r2))
print('r2 >= r3 = ' + str(r2 >= r3))
print('r3 >= r4 = ' + str(r3 >= r4))
print('r4 >= r5 = ' + str(r4 >= r5))
print('r5 >= r6 = ' + str(r5 >= r6))
print('')
print('greater')
print('r0 > r1 = ' + str(r0 > r1))
print('r1 > r2 = ' + str(r1 > r2))
print('r2 > r3 = ' + str(r2 > r3))
print('r3 > r4 = ' + str(r3 > r4))
print('r4 > r5 = ' + str(r4 > r5))
print('r5 > r6 = ' + str(r5 > r6))
print('')
print('-----------------------')
print('interval:')
print('')
print('id')
print('i0 = ' + str(i0))
print('i1 = ' + str(i1))
print('i2 = ' + str(i2))
print('i3 = ' + str(i3))
print('i4 = ' + str(i4))
print('i5 = ' + str(i5))
print('i6 = ' + str(i6))
print('i7 = ' + str(i7))
print('i8 = ' + str(i8))
print('i9 = ' + str(i9))
print('-----------------------')
print('')
print(str(e0) + ' or ' + str(i1) + ' = ' + str(e0 | i1))
print('not ' + str(i1) + ' = ' + str(~i1))
print(str(e0) + ' and ' + str(i1) + ' = ' + str(e0 & i1))
print(str(e0) + ' or ' + str(i2) + ' = ' + str(e0 | i2))
print('not ' + str(i2) + ' = ' + str(~i2))
print(str(e0) + ' and ' + str(i2) + ' = ' + str(e0 & i2))
print(str(i1) + ' or ' + str(i2) + ' = ' + str(i1 | i2))
print(str(i2) + ' or ' + str(i1) + ' = ' + str(i2 | i1))
print(str(i1) + ' and ' + str(i2) + ' = ' + str(i1 & i2))
print(str(i2) + ' and ' + str(i1) + ' = ' + str(i2 & i1))
print('not ' + str(i7) + ' = ' + str(~i7))
print(str(e1) + ' and ' + str(i7) + ' = ' + str(e1 & i7))
print(str(e1) + ' in ' + str(i7) + ' = ' + str(e1 in i7))
print(str(i7) + ' in ' + str(e1) + ' = ' + str(i7 in e1))
print(str(i7) + ' or ' + str(i11) + ' = ' + str(i7 | i11))
print(str(e0 | i10 | i11) + ' and ' + str(i12) + ' = ' + str((e0 | i10 | i11) & i12))
print(str(i13) + ' and ' + str(i14) + ' = ' + str(i13 & i14))
print(str(i13) + ' minus ' + str(i14), end=' ')
i13.remove(i14[0])
print(i13)
